spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhostMySQL:3306/netschool?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.edu.hfut.net.netschool.model
server:
  port: 8080
